import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, PageBreak } from 'docx'
import { saveAs } from 'file-saver'

// ===== DOCX Export =====

function parseMarkdown(markdown) {
  const lines = markdown.split('\n')
  const elements = []
  let currentTable = null

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()
    
    // Table detection
    if (line.startsWith('|') && line.endsWith('|')) {
      if (line.includes('---')) continue // Skip separator line
      const cells = line.split('|').filter(c => c.trim().length > 0 || line.includes('||')).map(c => c.trim())
      if (!currentTable) {
        currentTable = { type: 'table', rows: [] }
        elements.push(currentTable)
      }
      currentTable.rows.push(cells)
      continue
    } else {
      currentTable = null
    }

    if (!line) { elements.push({ type: 'p', text: '' }); continue }
    
    if (line.startsWith('### ')) elements.push({ type: 'h3', text: line.replace(/^### /, '') })
    else if (line.startsWith('## ')) elements.push({ type: 'h2', text: line.replace(/^## /, '') })
    else if (line.startsWith('# ')) elements.push({ type: 'h1', text: line.replace(/^# /, '') })
    else if (line.startsWith('- ') || line.startsWith('* ')) elements.push({ type: 'li', text: line.replace(/^[-*] /, '') })
    else elements.push({ type: 'p', text: line.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1') })
  }
  return elements
}

function elementsToDocx(elements) {
  const children = []
  elements.forEach((el, idx) => {
    if (el.type === 'table') {
      const table = new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: el.rows.map((row, rIdx) => new TableRow({
          children: row.map((cell, cIdx) => new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: cell, size: 18, bold: rIdx === 0 })],
              alignment: AlignmentType.CENTER
            })],
            shading: {
              fill: rIdx === 0 ? 'F2F2F2' : (cIdx === 0 ? (Math.floor(rIdx/2)%2 === 0 ? 'FFCC99' : 'C6E0B4') : 'FFFFFF'),
            },
            verticalAlign: AlignmentType.CENTER,
          })),
        })),
      })
      children.push(table)
      children.push(new Paragraph({ text: '' }))
    } else if (el.type === 'h1') children.push(new Paragraph({ text: el.text, heading: HeadingLevel.HEADING_1, spacing: { before: 400 } }))
    else if (el.type === 'h2') children.push(new Paragraph({ text: el.text, heading: HeadingLevel.HEADING_2, spacing: { before: 300 } }))
    else if (el.type === 'h3') children.push(new Paragraph({ text: el.text, heading: HeadingLevel.HEADING_3, spacing: { before: 200 } }))
    else if (el.type === 'li') children.push(new Paragraph({ text: el.text, bullet: { level: 0 } }))
    else children.push(new Paragraph({ children: [new TextRun({ text: el.text, font: 'Segoe UI' })] }))
  })
  return children
}

export async function exportToDocx({ title, content, filename = 'document', schoolName = 'Teacher\'s Pet', subject = '', grade = '' }) {
  const primaryColor = '0078D4' // Office Blue
  
  const headerParagraphs = [
    new Paragraph({
      children: [new TextRun({ text: schoolName.toUpperCase(), bold: true, size: 24, color: primaryColor, font: 'Segoe UI' })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: `${subject}${grade ? ' | ' + grade : ''}`, size: 18, color: '666666', font: 'Segoe UI' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 }
    }),
    new Paragraph({
      border: { bottom: { color: primaryColor, space: 1, style: BorderStyle.SINGLE, size: 6 } },
      children: []
    }),
    new Paragraph({ text: '', spacing: { before: 200 } }),
    new Paragraph({
      children: [new TextRun({ text: title, bold: true, size: 36, color: '000000', font: 'Segoe UI' })],
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.LEFT,
    }),
    new Paragraph({ text: '', spacing: { before: 200 } }),
  ]

  const doc = new Document({
    sections: [{
      properties: { 
        page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } 
      },
      headers: {
        default: new Paragraph({
          children: [new TextRun({ text: `${schoolName} — ${title}`, size: 16, color: '999999' })],
          alignment: AlignmentType.RIGHT,
        }),
      },
      footers: {
        default: new Paragraph({
          children: [new TextRun({ text: `Generated by Teacher's Pet AI — ${new Date().toLocaleDateString()}`, size: 16, color: '999999' })],
          alignment: AlignmentType.CENTER,
        }),
      },
      children: [...headerParagraphs, ...elementsToDocx(parseMarkdown(content))],
    }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${filename}.docx`)
}

// ===== PDF Export (html2canvas + jsPDF) =====
export async function exportToPDF(elementId, filename = 'document') {
  const { default: html2canvas } = await import('html2canvas')
  const { default: jsPDF } = await import('jspdf')

  const element = document.getElementById(elementId)
  if (!element) return

  // Determine background color based on theme or default to white for print
  const theme = document.documentElement.getAttribute('data-theme')
  const bgColor = (theme === 'dark' || theme === 'midnight') ? '#121212' : '#FFFFFF'
  const textColor = (theme === 'dark' || theme === 'midnight') ? '#FFFFFF' : '#000000'

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: bgColor,
    logging: false,
    onclone: (clonedDoc) => {
      const el = clonedDoc.getElementById(elementId)
      el.style.color = textColor
      el.style.padding = '40px'
      el.style.borderRadius = '0'
      el.style.background = bgColor
    }
  })

  const imgData = canvas.toDataURL('image/png')
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pdfWidth = pdf.internal.pageSize.getWidth()
  const pdfHeight = (canvas.height * pdfWidth) / canvas.width

  let yOffset = 0
  const pageHeight = pdf.internal.pageSize.getHeight()
  while (yOffset < pdfHeight) {
    if (yOffset > 0) pdf.addPage()
    pdf.addImage(imgData, 'PNG', 0, -yOffset, pdfWidth, pdfHeight)
    yOffset += pageHeight
  }

  pdf.save(`${filename}.pdf`)
}

// ===== CSV Export =====
export function exportToCSV(data, filename = 'data') {
  if (!data.length) return
  const headers = Object.keys(data[0])
  const rows = data.map(row => headers.map(h => `"${String(row[h] ?? '').replace(/"/g, '""')}"`).join(','))
  const csv = [headers.join(','), ...rows].join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  saveAs(blob, `${filename}.csv`)
}

// ===== Template Upload Parser =====
export async function parseDocxTemplate(file) {
  const mammoth = await import('mammoth')
  const buffer = await file.arrayBuffer()
  const result = await mammoth.extractRawText({ arrayBuffer: buffer })
  return result.value
}
